// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zhoverulwcybtgrezaob.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpob3ZlcnVsd2N5YnRncmV6YW9iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM5MTA5ODAsImV4cCI6MjA4OTQ4Njk4MH0.YF5MU9LB0fphsS4nu52P9-kXsswF27NOSzLTb3GdPag";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});